### ISSUE TITLE
Component not rendering

### ISSUE THREAD

**Issue by ndarilek** [maliknoorhassan/vue-languages-dropdown#1]
I'm not familiar with how Vue plugins work, but I'm looking at this code:

```
        Vue.component(DropDown.name, DropDown);
```

Nothing I do seems to render this component, and I get no errors in the console. I've followed the example from the README fairly closely, i.e.:

```
import LanguageDropdown from "vue-languages-dropdown"

Vue.use(LanguageDropdown)

          <language-dropdown selected="en" :languages="supportedLanguages"/>
```

It looks to me like the component may be called `DropDown` and there isn't a way to override that? Is this accurate? I've never written a Vue plugin before, so maybe I'm missing something.

Thanks.

**Comment by maliknoorhassan** [comment]
Fixed in v 1.0.16, now it's simple vue component. Thanks for pointing out once again.
