### ISSUE TITLE
Importing in any view overwrites all project text classes

### ISSUE THREAD

**Issue by titusdecali** [maliknoorhassan/vue-languages-dropdown#2]
I am using the Shards UI kit for a Vue project.

Simply importing vue-languages-dropdown into a view changes all text-related classes.
I can overwrite some by using the '*' class within a scoped statement, but this should really be scoped into just the imported component itself to begin with.

**Comment by maliknoorhassan** [comment]
Fixed in 2b43a20a1a9cb90b3aed8730dcc23f89c348b1c1
