### ISSUE TITLE
Show selected item in native language

### ISSUE THREAD

**Issue by Truemedia** [maliknoorhassan/vue-languages-dropdown#3]
Hi,
Managed to get this component working on my own website today thanks. There is just one small feature I would like to request or nake a PR for.

In my instance I show the users native language in the dropdown, so was thinking it would make sense to have an extra component option to allow the selected item to be shown in it's native language aswell when selected

**Comment by maliknoorhassan** [comment]
Hello @Truemedia ,
Thanks for your valuable suggestion, Sorry for the delay, I was busy other stuff. Just introduces a new option `showSelectedNative` in 5d6b0e01abf04a50e641d7eb52030aefefbcdc1a
